name: Release on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Match semantic version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test ./... -v

      - name: Extract latest changelog entry
        run: |
          awk '/^## v[0-9]+\.[0-9]+\.[0-9]+/ { if (found) exit; found=1 } found' CHANGELOG.md > .release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: .release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}